stages:
  - test
  - build
  - deploy

# lint-test-job:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - pip install flake8
#     - flake8 ripe_tomatoes

# ripe-tomatoes-unit-test-job:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - cd ripe_tomatoes
#     - pip install -r requirements.txt
#     - python -m pytest

services:
  - postgres:14.2-bullseye

variables:
  DATABASE_URL: postgresql://postgres:86ea4e15c8c4bf90@http://srv-captain--ripe-tomatoes-db/postgres

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  # needs:
  # - ripe-tomatoes-unit-test-job
  #   - lint-test-job
  variables:
    PUBLIC_URL: https://ripe-tomatoes.gitlab.io/ripe-tomatoes
    REACT_APP_RIPE_TOMATOES_API_HOST: http://ripe-tomatoes.sept-ct-5.mod3projects.com
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

build-api-backend:
  image: docker:19.03.1
  stage: build
  variables:
    CORS_HOST: https://ripe-tomatoes.gitlab.io
  services:
    - docker:19.03.1-dind
  before_script:
    - export DOCKER_REGISTRY_USER=$CI_REGISTRY_USER # built-in GitLab Registry User
    - export DOCKER_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD # built-in GitLab Registry Password
    - export DOCKER_REGISTRY_URL=$CI_REGISTRY # built-in GitLab Registry URL
    - export COMMIT_HASH=$CI_COMMIT_SHA # Your current commit sha
    - export IMAGE_NAME_WITH_REGISTRY_PREFIX=$CI_REGISTRY_IMAGE # Your repository prefixed with GitLab Registry URL
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY_URL # Instructs GitLab to login to its registry

  script:
    - cd ripe_tomatoes
    - echo "Building..." # MAKE SURE NO SPACE ON EITHER SIDE OF = IN THE FOLLOWING LINE
    - export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$IMAGE_NAME_WITH_REGISTRY_PREFIX/ripe_tomatoes:$COMMIT_HASH
    - docker build -f ./Dockerfile --pull -t ripe_tomatoes_img .
    - docker tag ripe_tomatoes_img "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - docker push "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - echo $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
    - echo "Deploying on CapRover..."
    - docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $CAPROVER_URL --caproverPassword $CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
  only:
    - main

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
